"""initial schema

Revision ID: 599dafc6cc34
Revises: 
Create Date: 2026-06-08 20:38:56.617640
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '599dafc6cc34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable PostGIS for geography / ST_* nearby queries. Guarded so the same
    # migration still runs on non-PostgreSQL backends (e.g. SQLite in dev/CI).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('best_time_to_visit', sa.String(length=500), nullable=True),
    sa.Column('average_budget_min', sa.Float(), nullable=True),
    sa.Column('average_budget_max', sa.Float(), nullable=True),
    sa.Column('safety_summary', sa.String(length=1000), nullable=True),
    sa.Column('weather_summary', sa.String(length=500), nullable=True),
    sa.Column('crowd_level', sa.String(length=50), nullable=True),
    sa.Column('internet_quality', sa.String(length=50), nullable=True),
    sa.Column('offline_available', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('trust_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_events_entity_id'), 'trust_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_trust_events_entity_type'), 'trust_events', ['entity_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('travel_style', sa.JSON(), nullable=True),
    sa.Column('diet_preference', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('offline_sync_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_changes', sa.JSON(), nullable=True),
    sa.Column('accepted_changes', sa.JSON(), nullable=True),
    sa.Column('conflicts', sa.JSON(), nullable=True),
    sa.Column('server_data_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_sync_logs_user_id'), 'offline_sync_logs', ['user_id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('cancellation_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_type'), 'partners', ['type'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geom_wkt', sa.Text(), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('diet_tags', sa.JSON(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('external_rating', sa.Float(), nullable=True),
    sa.Column('external_review_count', sa.Integer(), nullable=True),
    sa.Column('external_rating_source', sa.String(length=100), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('tripova_score', sa.Float(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('food_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_place_id', sa.String(length=255), nullable=True),
    sa.Column('is_partner_listed', sa.Boolean(), nullable=True),
    sa.Column('is_offline_available', sa.Boolean(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_destination_id'), 'places', ['destination_id'], unique=False)
    op.create_index(op.f('ix_places_popularity_score'), 'places', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_places_slug'), 'places', ['slug'], unique=False)
    op.create_index(op.f('ix_places_tripova_score'), 'places', ['tripova_score'], unique=False)
    op.create_index(op.f('ix_places_type'), 'places', ['type'], unique=False)
    op.create_table('trip_pods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('travel_style', sa.JSON(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('gender_preference', sa.String(length=50), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_pods_creator_id'), 'trip_pods', ['creator_id'], unique=False)
    op.create_index(op.f('ix_trip_pods_status'), 'trip_pods', ['status'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('trip_type', sa.String(length=50), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('people_count', sa.Integer(), nullable=True),
    sa.Column('travel_style', sa.JSON(), nullable=True),
    sa.Column('diet_preference', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_required', sa.Boolean(), nullable=True),
    sa.Column('generated_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('deep_review_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('place_id', sa.Uuid(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('sources_used', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deep_review_queries_place_id'), 'deep_review_queries', ['place_id'], unique=False)
    op.create_table('feed_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('place_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('crowd_level', sa.String(length=50), nullable=True),
    sa.Column('weather_note', sa.String(length=500), nullable=True),
    sa.Column('safety_note', sa.String(length=500), nullable=True),
    sa.Column('price_note', sa.String(length=500), nullable=True),
    sa.Column('food_note', sa.String(length=500), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_posts_destination_id'), 'feed_posts', ['destination_id'], unique=False)
    op.create_index(op.f('ix_feed_posts_user_id'), 'feed_posts', ['user_id'], unique=False)
    op.create_table('food_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('diet_tag', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_verifications_diet_tag'), 'food_verifications', ['diet_tag'], unique=False)
    op.create_index(op.f('ix_food_verifications_place_id'), 'food_verifications', ['place_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_partner_id'), 'listings', ['partner_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('offline_packs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('pack_json', sa.JSON(), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_packs_user_id'), 'offline_packs', ['user_id'], unique=False)
    op.create_table('place_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('place_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_place_id', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('raw_category', sa.String(length=255), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_sources_place_id'), 'place_sources', ['place_id'], unique=False)
    op.create_table('trip_pod_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_pod_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_pod_id'], ['trip_pods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_pod_members_trip_pod_id'), 'trip_pod_members', ['trip_pod_id'], unique=False)
    op.create_index(op.f('ix_trip_pod_members_user_id'), 'trip_pod_members', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=True),
    sa.Column('partner_id', sa.Uuid(), nullable=True),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_trip_pod_members_user_id'), table_name='trip_pod_members')
    op.drop_index(op.f('ix_trip_pod_members_trip_pod_id'), table_name='trip_pod_members')
    op.drop_table('trip_pod_members')
    op.drop_index(op.f('ix_place_sources_place_id'), table_name='place_sources')
    op.drop_table('place_sources')
    op.drop_index(op.f('ix_offline_packs_user_id'), table_name='offline_packs')
    op.drop_table('offline_packs')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_partner_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_food_verifications_place_id'), table_name='food_verifications')
    op.drop_index(op.f('ix_food_verifications_diet_tag'), table_name='food_verifications')
    op.drop_table('food_verifications')
    op.drop_index(op.f('ix_feed_posts_user_id'), table_name='feed_posts')
    op.drop_index(op.f('ix_feed_posts_destination_id'), table_name='feed_posts')
    op.drop_table('feed_posts')
    op.drop_index(op.f('ix_deep_review_queries_place_id'), table_name='deep_review_queries')
    op.drop_table('deep_review_queries')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_trip_pods_status'), table_name='trip_pods')
    op.drop_index(op.f('ix_trip_pods_creator_id'), table_name='trip_pods')
    op.drop_table('trip_pods')
    op.drop_index(op.f('ix_places_type'), table_name='places')
    op.drop_index(op.f('ix_places_tripova_score'), table_name='places')
    op.drop_index(op.f('ix_places_slug'), table_name='places')
    op.drop_index(op.f('ix_places_popularity_score'), table_name='places')
    op.drop_index(op.f('ix_places_destination_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_partners_type'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_offline_sync_logs_user_id'), table_name='offline_sync_logs')
    op.drop_table('offline_sync_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trust_events_entity_type'), table_name='trust_events')
    op.drop_index(op.f('ix_trust_events_entity_id'), table_name='trust_events')
    op.drop_table('trust_events')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
